name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload files to GCS
        run: |
          gsutil cp index.html gs://cloud-course-sagar-2026/
          gsutil cp about.html gs://cloud-course-sagar-2026/
          gsutil cp style.css gs://cloud-course-sagar-2026/